from django.conf import settings

CMS_VIMEO_DEFAULT_WIDTH = getattr(settings, 'CMS_VIMEO_DEFAULT_WIDTH', 500)
CMS_VIMEO_DEFAULT_HEIGHT = getattr(settings, 'CMS_VIMEO_DEFAULT_HEIGHT', 375)
CMS_VIMEO_DEFAULT_AUTOPLAY = getattr(settings, 'CMS_VIMEO_DEFAULT_AUTOPLAY', False)
CMS_VIMEO_DEFAULT_LOOP = getattr(settings, 'CMS_VIMEO_DEFAULT_LOOP', False)
CMS_VIMEO_DEFAULT_SHOW_TITLE = getattr(settings, 'CMS_VIMEO_DEFAULT_SHOW_TITLE', True)
CMS_VIMEO_DEFAULT_SHOW_PORTRAIT = getattr(settings, 'CMS_VIMEO_DEFAULT_SHOW_PORTRAIT', True)
CMS_VIMEO_DEFAULT_SHOW_BYLINE = getattr(settings, 'CMS_VIMEO_DEFAULT_SHOW_BYLINE', False)
CMS_VIMEO_DEFAULT_SECURE = getattr(settings, 'CMS_VIMEO_DEFAULT_SECURE', True)
CMS_VIMEO_DEFAULT_TITLE_COLOR = getattr(settings, 'CMS_VIMEO_DEFAULT_TITLE_COLOR', 'ffffff')

